### ISSUE TITLE
Stacks Connect Error

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#71]
Experiencing this error on `https://testnet.stx.eco`.

This prevents deployment to TM servers - ie we may break the site currently hosted at https://sbtc-bridge.pages.dev/ if we try and push this code. Note this means the PSBT integration is not yet publicly available. 

This error is only present on the production build - ie the site works fine when running via `npm run dev` on localhost.

```
Uncaught (in promise) TypeError: Assignment to constant variable.
    at _regeneratorRuntime2 (stacks_connect.b4d56166.js:8113:26)
    at stacks_connect.b4d56166.js:8507:34
    at stacks_connect.b4d56166.js:8568:4
    at stacks_connect.b4d56166.js:9926:3
```

**Comment by radicleart** [comment]
During investigation came across a warning that might be relevant to stacksjs...

```
Export "principalCV" of module "node_modules/@stacks/transactions/dist/esm/clarity/types/principalCV.js" was reexported through module "node_modules/@stacks/transactions/dist/esm/clarity/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "src/lib/sbtc_admin.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "tupleCV" of module "node_modules/@stacks/transactions/dist/esm/clarity/types/tupleCV.js" was reexported through module "node_modules/@stacks/transactions/dist/esm/clarity/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "src/lib/sbtc_admin.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

**Comment by radicleart** [comment]
Tracked this down to use of a vite plugin

```
import topLevelAwait from "vite-plugin-top-level-await";
...
  plugins: [
    sveltekit(),
    topLevelAwait()
  ],
```

**Comment by radicleart** [comment]
Tested on linode and appears fixed.

**Comment by igorsyl** [comment]
@radicleart let's create a new branch: 'prod'. We'll use this for the prod deployment.
cc @sergey-shandar
